# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bridge To China

description: >- # this means to ignore newlines until "baseurl:"
  Change your life. Experience a new culture. Travel the world. Join us now!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bridge2china.co.uk" # the base hostname & protocol for your site, e.g. http://example.com

logo:                  /icons/bridge.png

author:
  name: Alex Stankovich
  social:
    #facebook: https://facebook.com/bridge2china
    #instagram: https://instagram.com/bridge2china

menu:
  - title:             About Us
    url:               /about/
  - title:             Opportunities
    url:               /opportunities/
  - title:             Recruitment Process
    url:               /recruitment/
  - title:             Contact Us
    url:               /contact/
  - title:             Apply Now
    url:               /apply/

copyright:             © 2019. All rights reserved.

accent_image:          /icons/china-pic.jpg
accent_color:          rgb(79,177,186)

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
